version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: master
    schedule:
      interval: "cron"
      cronjob: "9 12 * 2,5,8,11 4#1"
    pull-request-branch-name:
      separator: "-"
