version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: master
    schedule:
      interval: "cron"
      cronjob: "9 12 1-7 2,5,8,11 4"
    pull-request-branch-name:
      separator: "-"
