repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.0.1'
    hooks:
      - id: end-of-file-fixer
        exclude: 'setup.cfg'
      - id: trailing-whitespace
        exclude: 'setup.cfg'
      - id: debug-statements
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v2.18.2'
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus
  - repo: https://github.com/pycqa/isort
    rev: '5.8.0'
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: '21.5b1'
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: '3.9.2'
    hooks:
      - id: flake8
        args:
          - --max-line-length=100
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.9.0
    hooks:
      - id: nbqa-pyupgrade
        args:
          - --nbqa-mutate
          - --py36-plus
      - id: nbqa-isort
        args:
          - --nbqa-mutate
      - id: nbqa-black
        args:
          - --nbqa-mutate
  - repo: https://github.com/bdice/nb-strip-paths
    rev: 'v0.1.0'
    hooks:
      - id: nb-strip-paths
