[workspace]
authors = ["Joshua A. Anderson <joaander@umich.edu>"]
channels = ["conda-forge"]
name = "freud-examples"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]

bokeh = "*"
fresnel = "*"
freud = "*"
gsd = "*"
hoomd = "*"
ipywidgets = "*"
jupyterlab = "*"
lammps = "*"
matplotlib = "*"
mdanalysis = "*"
mdtraj = "*"
nbconvert = "*"
networkx = "*"
notebook = "*"
numpy = "*"
pillow = "*"
pip = "*"
pre-commit = "*"
pythreejs = "*"
scipy = "*"
tqdm = "*"
